"""Initial migration with consistent id_key

Revision ID: 7de0ce4d4887
Revises: 
Create Date: 2025-12-11 22:15:03.742514

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7de0ce4d4887'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('addresses',
    sa.Column('id_key', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('street', sa.String(length=200), nullable=True),
    sa.Column('city', sa.String(length=100), nullable=True),
    sa.Column('state', sa.String(length=100), nullable=True),
    sa.Column('zip_code', sa.String(length=20), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id_key')
    )
    op.create_index(op.f('ix_addresses_id_key'), 'addresses', ['id_key'], unique=False)
    op.create_table('categories',
    sa.Column('id_key', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id_key')
    )
    op.create_index(op.f('ix_categories_id_key'), 'categories', ['id_key'], unique=False)
    op.create_index(op.f('ix_categories_name'), 'categories', ['name'], unique=True)
    op.create_table('orders',
    sa.Column('id_key', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('date', sa.DateTime(), nullable=True),
    sa.Column('total', sa.Float(), nullable=True),
    sa.Column('delivery_method', sa.Enum('DRIVE_THRU', 'ON_HAND', 'HOME_DELIVERY', name='deliverymethod'), nullable=True),
    sa.Column('status', sa.Enum('PENDING', 'IN_PROGRESS', 'DELIVERED', 'CANCELED', name='status'), nullable=True),
    sa.Column('client_id_key', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['client_id_key'], ['clients.id_key'], ),
    sa.PrimaryKeyConstraint('id_key')
    )
    op.create_index(op.f('ix_orders_client_id_key'), 'orders', ['client_id_key'], unique=False)
    op.create_index(op.f('ix_orders_date'), 'orders', ['date'], unique=False)
    op.create_index(op.f('ix_orders_delivery_method'), 'orders', ['delivery_method'], unique=False)
    op.create_index(op.f('ix_orders_id_key'), 'orders', ['id_key'], unique=False)
    op.create_index(op.f('ix_orders_status'), 'orders', ['status'], unique=False)
    op.create_table('products',
    sa.Column('id_key', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('price', sa.Float(), nullable=False),
    sa.Column('stock', sa.Integer(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('category_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['category_id'], ['categories.id_key'], ),
    sa.PrimaryKeyConstraint('id_key')
    )
    op.create_index(op.f('ix_products_category_id'), 'products', ['category_id'], unique=False)
    op.create_index(op.f('ix_products_id_key'), 'products', ['id_key'], unique=False)
    op.create_index(op.f('ix_products_name'), 'products', ['name'], unique=False)
    op.create_index(op.f('ix_products_price'), 'products', ['price'], unique=False)
    op.create_index(op.f('ix_products_stock'), 'products', ['stock'], unique=False)
    op.create_table('bills',
    sa.Column('id_key', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('bill_number', sa.String(), nullable=False),
    sa.Column('discount', sa.Float(), nullable=True),
    sa.Column('date', sa.Date(), nullable=True),
    sa.Column('total', sa.Float(), nullable=True),
    sa.Column('payment_type', sa.Enum('CASH', 'CARD', 'DEBIT', 'CREDIT', 'BANK_TRANSFER', name='paymenttype'), nullable=True),
    sa.Column('client_id_key', sa.Integer(), nullable=True),
    sa.Column('order_id_key', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['client_id_key'], ['clients.id_key'], ),
    sa.ForeignKeyConstraint(['order_id_key'], ['orders.id_key'], ),
    sa.PrimaryKeyConstraint('id_key')
    )
    op.create_index(op.f('ix_bills_bill_number'), 'bills', ['bill_number'], unique=True)
    op.create_index(op.f('ix_bills_client_id_key'), 'bills', ['client_id_key'], unique=False)
    op.create_index(op.f('ix_bills_id_key'), 'bills', ['id_key'], unique=False)
    op.create_index(op.f('ix_bills_order_id_key'), 'bills', ['order_id_key'], unique=False)
    op.create_table('order_details',
    sa.Column('id_key', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=True),
    sa.Column('price', sa.Float(), nullable=True),
    sa.Column('order_id', sa.Integer(), nullable=True),
    sa.Column('product_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id_key'], ),
    sa.ForeignKeyConstraint(['product_id'], ['products.id_key'], ),
    sa.PrimaryKeyConstraint('id_key')
    )
    op.create_index(op.f('ix_order_details_id_key'), 'order_details', ['id_key'], unique=False)
    op.create_index(op.f('ix_order_details_order_id'), 'order_details', ['order_id'], unique=False)
    op.create_index(op.f('ix_order_details_product_id'), 'order_details', ['product_id'], unique=False)
    op.create_table('reviews',
    sa.Column('id_key', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('rating', sa.Float(), nullable=False),
    sa.Column('comment', sa.String(), nullable=True),
    sa.Column('product_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.CheckConstraint('rating >= 1.0 AND rating <= 5.0', name='check_rating_range'),
    sa.ForeignKeyConstraint(['product_id'], ['products.id_key'], ),
    sa.PrimaryKeyConstraint('id_key')
    )
    op.create_index(op.f('ix_reviews_id_key'), 'reviews', ['id_key'], unique=False)
    op.create_index(op.f('ix_reviews_product_id'), 'reviews', ['product_id'], unique=False)
    op.drop_constraint('clients_email_key', 'clients', type_='unique')
    op.create_index(op.f('ix_clients_email'), 'clients', ['email'], unique=True)
    op.create_index(op.f('ix_clients_id_key'), 'clients', ['id_key'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_clients_id_key'), table_name='clients')
    op.drop_index(op.f('ix_clients_email'), table_name='clients')
    op.create_unique_constraint('clients_email_key', 'clients', ['email'])
    op.drop_index(op.f('ix_reviews_product_id'), table_name='reviews')
    op.drop_index(op.f('ix_reviews_id_key'), table_name='reviews')
    op.drop_table('reviews')
    op.drop_index(op.f('ix_order_details_product_id'), table_name='order_details')
    op.drop_index(op.f('ix_order_details_order_id'), table_name='order_details')
    op.drop_index(op.f('ix_order_details_id_key'), table_name='order_details')
    op.drop_table('order_details')
    op.drop_index(op.f('ix_bills_order_id_key'), table_name='bills')
    op.drop_index(op.f('ix_bills_id_key'), table_name='bills')
    op.drop_index(op.f('ix_bills_client_id_key'), table_name='bills')
    op.drop_index(op.f('ix_bills_bill_number'), table_name='bills')
    op.drop_table('bills')
    op.drop_index(op.f('ix_products_stock'), table_name='products')
    op.drop_index(op.f('ix_products_price'), table_name='products')
    op.drop_index(op.f('ix_products_name'), table_name='products')
    op.drop_index(op.f('ix_products_id_key'), table_name='products')
    op.drop_index(op.f('ix_products_category_id'), table_name='products')
    op.drop_table('products')
    op.drop_index(op.f('ix_orders_status'), table_name='orders')
    op.drop_index(op.f('ix_orders_id_key'), table_name='orders')
    op.drop_index(op.f('ix_orders_delivery_method'), table_name='orders')
    op.drop_index(op.f('ix_orders_date'), table_name='orders')
    op.drop_index(op.f('ix_orders_client_id_key'), table_name='orders')
    op.drop_table('orders')
    op.drop_index(op.f('ix_categories_name'), table_name='categories')
    op.drop_index(op.f('ix_categories_id_key'), table_name='categories')
    op.drop_table('categories')
    op.drop_index(op.f('ix_addresses_id_key'), table_name='addresses')
    op.drop_table('addresses')
    # ### end Alembic commands ###
