"""Add client_id_key to addresses

Revision ID: d3e300937de7
Revises: 7de0ce4d4887
Create Date: 2025-12-11 22:43:07.433237

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd3e300937de7'
down_revision: Union[str, None] = '7de0ce4d4887'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('addresses', sa.Column('client_id_key', sa.Integer(), nullable=False))
    op.create_index(op.f('ix_addresses_client_id_key'), 'addresses', ['client_id_key'], unique=False)
    op.create_foreign_key(None, 'addresses', 'clients', ['client_id_key'], ['id_key'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'addresses', type_='foreignkey')
    op.drop_index(op.f('ix_addresses_client_id_key'), table_name='addresses')
    op.drop_column('addresses', 'client_id_key')
    # ### end Alembic commands ###
